### ISSUE TITLE
404 url in https://github.com/minvws/nl-kat-rocky#stack

### ISSUE THREAD

**Issue by MartenVijnNaturalis** [minvws/nl-kat-rocky#13]
### Describe the bug, issue or concern

https://github.com/minvws/nl-kat-rocky#stack  link to manon end in 404 msg in github
see screenshot 

kind regards Marten

![Screenshot from 2022-08-13 16-49-09](https://user-images.githubusercontent.com/44702073/184499341-93e84a88-b24b-4f25-847a-2734f649db8f.png)

**Comment by underdarknl** [comment]
Dear @MartenVijnNaturalis 
The correct url is https://github.com/minvws/nl-rdo-manon
We will fix the docs to point to this url.

Thanks for finding this issue, and I hope you enjoy OpenKAT and Manon.

**Comment by noamblitz** [comment]
https://github.com/minvws/nl-kat-rocky/pull/19

Fixed with this PR
