### ISSUE TITLE
[OpenKAT v1.6]  (re)Design: Lo-Fi filters layout on OOI overview

### ISSUE THREAD

**Issue by TwistMeister** [minvws/nl-kat-rocky#142]
Design a way to show three filter options in the filter box:

    1. OOI types
    2. Scan profile
            1. Type (max 3 opties)
                1. Inherited
                2. Declared
            2. Level (5 opties)
    3. OOI origin (max 4 opties)
            1. Declared
            2. Inherited
            3. Observed

**Comment by NoemiOverdijk** [comment]
We discovered there is already a functional design for this, so a lo-fi redesign is no longer needed.
