### ISSUE TITLE
[OpenKAT 1.6] Add step in onboarding flow, "user adds evidence" which results in OOI, instead of creating an OOI manually

### ISSUE THREAD

**Issue by TwistMeister** [minvws/nl-kat-rocky#148]
When declared OOI's will be put trough Bytes, the steps in the onboarding flow (and manual creation flow) should be changed slightly.

Rocky should post a "ooi-json" to Bytes instead of a "OOI" to Octopoes.
```
"ooi": {
    "object_type": "Network",
    "scan_profile": null,
    "primary_key": "Network|internet",
    "name": "internet"
  }
```

Also CSV upload should post the raw CSV to Bytes.

**Comment by Donnype** [comment]
@TwistMeister See the update I posted in https://github.com/minvws/nl-kat-boefjes/issues/67 : I think this might no longer needs refinement or Frontend work.
