### ISSUE TITLE
Error building rocky-frontend container

### ISSUE THREAD

**Issue by klaver** [minvws/nl-kat-rocky#6]
On a fresh Debian 11 system, following the manual exactly, running the 'make kat' command results in this error:

make build-rocky-frontend
make[1]: Entering directory '/app/rocky'
yarn
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
error Could not write file "/app/rocky/yarn-error.log": "EACCES: permission denied, open '/app/rocky/yarn-error.log'"
error An unexpected error occurred: "EACCES: permission denied, mkdir '/app/rocky/node_modules'".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
make[1]: *** [Makefile:21: build-rocky-frontend] Error 1
make[1]: Leaving directory '/app/rocky'
make: *** [Makefile:10: build] Error 2
ERROR: 2

**Comment by underdarknl** [comment]
Dear @klaver we might have found the underlying issue, are you by any change running and building `make kat` on a userID other than 1000, eg the first user?

**Comment by klaver** [comment]
yes, my userID comes from an LDAP auth-system which is in a totally different range than traditional local Linux user accounts

**Comment by klaver** [comment]
Created a local user with UID 1000, 'make kat' runs fine using that new user (also, I was using sudo previously and maybe shoudn't do that)

**Comment by Darwinkel** [comment]
@klaver A fix for this will be published in the next release.

**Comment by underdarknl** [comment]
Dear @klaver we think the current release (1.1) should have fixed this issue.
